# https://taskfile.dev

version: '3'

vars:
  TEST: test

tasks:
  default:
    cmds:
      - task --list-all

  build:
    cmds:
      - ./gradlew build

  test:
    cmds:
      - ./gradlew test

  format:
    cmds:
      - ./gradlew ktfmtFormat

  runIde:
    desc: Run the latest IDE (manual testing)
    cmds:
      - ./gradlew runIdeLatest

  runIdeMin:
    desc: Run the minimum supported IDE (compile target)
    cmds:
      - ./gradlew runIde

  print:
    cmds:
      - cat Taskfile.yml
      - echo TEST={{.TEST}} TEST2={{.TEST2}}

  bg-task:
    desc: Run a background task
    cmds:
      - sleep 300 &
      - echo done