# https://taskfile.dev

version: '3'

vars:
  TEST: test

tasks:
  default:
    cmds:
      - task --list-all

  build:
    desc: Build plugin
    cmds:
      - ./gradlew build

  format:
    desc: Format source code with ktfmt
    cmds:
      - ./gradlew ktfmtFormat

  runIde:
    desc: Run IDE with this plugin
    cmds:
      - ./gradlew runIde

  print:
    cmds:
      - cat Taskfile.yml
      - echo TEST={{.TEST}} TEST2={{.TEST2}}
