# https://taskfile.dev

version: '3'

vars:
  TEST: test

tasks:
  build:
    cmds:
      - ./gradlew build

  buildPlugin:
    cmds:
      - ./gradlew buildPlugin

  runIde:
    cmds:
      - ./gradlew runIde

  print:
    cmds:
      - cat Taskfile.yml
      - echo TEST={{.TEST}} TEST2={{.TEST2}}
