# https://taskfile.dev

version: '3'

vars:
  TEST: test

tasks:
  build:
    cmds:
      - ./gradlew build

  runIde:
    cmds:
      - ./gradlew runIde

  print:
    cmds:
      - cat Taskfile.yml
      - echo TEST={{.TEST}} TEST2={{.TEST2}}

  sudo_print:
    cmds:
      - sudo echo TEST={{.TEST}} TEST2={{.TEST2}}
    interactive: true
