on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true

      - name: Build
        run: ./gradlew clean build

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/distributions/*.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Release ${{ env.RELEASE_VERSION }}
            Install : Preferences -> Plugin -> Install Plugin from Disk

      - name: Publish plugin
        run: ./gradlew publishPlugin
        env:
          ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.PUBLISH_TOKEN }}
